proxy:
  image: kazunoriboy/proxy:1.0
  links:
    - identidock
  ports:
    - "80:80"
  environment:
    - NGINX_HOST=identidock.com
    - NGINX_PROXY=http://identidock:9090
  identidock:
    image: kazunoriboy/identidock:1.0
    links:
      - dnmonster
      - redis
    environment:
      ENV: PROD
    dnmonster:
      image: amouat/dnmonster
    redis:
      image: redis
    logspout:
      image: amouat/logspout-logstash
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock
      ports:
        - "8000:80"

